name: altsome_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Core & UI
  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  logger: ^2.3.0
  shared_preferences: ^2.2.3
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  uuid: ^4.4.0
  url_launcher: ^6.3.0

  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.7

  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  cloud_functions: ^5.6.2

  # Utilities
  flutter_image_compress: ^2.3.0
  expandable_page_view: ^1.0.17
  http: ^1.2.1
  image_picker: ^1.1.2
  email_validator: ^2.1.17
  cached_network_image: ^3.3.1
  dots_indicator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/onboarding/
