name: altsome_app
description: "A new Flutter project."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.6.1
  go_router: ^16.0.0
  supabase_flutter: ^2.9.1
  logger: ^2.6.1
  equatable: ^2.0.7
  flutter_image_compress: ^2.4.0
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  expandable_page_view: ^1.0.17
  http: ^1.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  uuid: ^4.5.0
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  hooks_riverpod: ^2.6.1
  email_validator: ^3.0.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1

  
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
 
  uses-material-design: true

  # assets:
  

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Medium.ttf
